### ISSUE TITLE
What is ABC in layers?

### ISSUE THREAD

**Issue by JACOBWHY** [jsonliu-szu/SSCF#1]
class TCE(nn.Module, ABC):

What is ABC here?
Waiting to be updated!

**Comment by jsonliu-szu** [comment]
https://blog.teclado.com/python-abc-abstract-base-classes
You can remove or add it.
We will not maintain the GitHub repository, if you have any questions, please email us directly.

**Comment by JACOBWHY** [comment]
Thank you for your prompt reply ！
Is this the right email address?&nbsp;I still have the following questions：


1.&nbsp;Will the complete code be open source?


2. What is 14 in PyramidSample?



&nbsp; &nbsp; &nbsp;There is only 1,3,5,7 in the paper.



3. Why is the number of&nbsp;channels restricted to max(4, C // 8)?
&nbsp; &nbsp; &nbsp;attention = aff.view(-1, max(4, C // 8))


4.What is FeatureExtraction module? Is it a general network like Resnet or VGG?



&nbsp; &nbsp; How do you achieve different weights for different encoders in the paper?


5. Why is the tranformation matrix T set like this, with 6 leanable parameters but not 9 learnable parameters?



&nbsp;and in the core code I&nbsp; only see these two conv as the transformation matrix, but the kernel_size is 1 not 3?






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "jsonliu-szu/SSCF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 中午11:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jsonliu-szu/SSCF] What is ABC in layers? (Issue #1)





 
https://blog.teclado.com/python-abc-abstract-base-classes
 You can remove or add it.
 We will not maintain the GitHub repository, if you have any questions, please email us directly.

**Comment by jsonliu-szu** [comment]
Hi, you can see our latest commit.
